name: chrome_api
description: A wrapper for the Chrome extension API to use the chrome handles inside dart.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies: 
  js: ^0.6.3
